name: Paks Build and Deploy
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        container: [["18.04"], ["20.04"], ["22.04"]]

    runs-on: ubuntu-latest
    container: ghcr.io/syspack/paks-ubuntu-${{ matrix.container[0] }}:latest
    name: Paks Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Package
        env:
          deploy: ${{ github.event_name != 'pull_request' }}
          package: .
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/pakages/paks
        run: /entrypoint.sh 
